version: "3.9"
services:
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: ${PG_PWD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  msvc-cursos:
    container_name: msvc-cursos
    image: ${USER_DOCKER_HUB}/courses:latest
    build:
      context: ../..
      dockerfile: ../../msvc-cursos/Dockerfile
    ports:
      - "8002:8002"
    environment:
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_US}
      DB_PASSWORD: ${DB_PWD}
      USUARIOS_URL: ${URL_US}
    networks:
      - spring
    depends_on:
      - postgres14
    restart: always

volumes:
  data-postgres:
    name: data-postgres

networks:
  spring:
    name: spring
